name: test

on:
  push:
    branches-ignore:
      - gh-pages
      - 'renovate/**'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22', '24']
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6.1.0

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test

      - run: pnpm run build

  test-pass:
    name: test-pass
    needs: [main]
    runs-on: ubuntu-slim
    steps:
      - run: 'true'
